CREATE TABLE IF NOT EXISTS sqlserver_blocking_log (
    id BIGSERIAL PRIMARY KEY,
    capture_time TIMESTAMPTZ,
    waiting_session_id INT,
    waiting_request_id INT,
    blocking_session_id INT,
    blocking_request_id INT,
    wait_type VARCHAR(120),
    wait_duration_ms BIGINT,
    resource_description TEXT,
    waiting_status VARCHAR(60),
    waiting_command VARCHAR(60),
    waiting_database_name VARCHAR(128),
    waiting_login_name VARCHAR(128),
    waiting_host_name VARCHAR(128),
    waiting_program_name VARCHAR(512),
    waiting_statement_text TEXT,
    blocking_status VARCHAR(60),
    blocking_command VARCHAR(60),
    blocking_database_name VARCHAR(128),
    blocking_login_name VARCHAR(128),
    blocking_host_name VARCHAR(128),
    blocking_program_name VARCHAR(512),
    blocking_statement_text TEXT
);
