CREATE TABLE IF NOT EXISTS sqlserver_activity_log (
    id BIGSERIAL PRIMARY KEY,
    capture_time TIMESTAMPTZ,
    session_id INT,
    request_id INT,
    blocking_session_id INT,
    status VARCHAR(60),
    command VARCHAR(60),
    database_name VARCHAR(128),
    login_name VARCHAR(128),
    host_name VARCHAR(128),
    program_name VARCHAR(512),
    start_time TIMESTAMPTZ,
    total_elapsed_ms BIGINT,
    cpu_time_ms BIGINT,
    logical_reads BIGINT,
    reads BIGINT,
    writes BIGINT,
    wait_type VARCHAR(60),
    wait_time_ms BIGINT,
    wait_resource VARCHAR(256),
    open_transaction_count INT,
    object_schema VARCHAR(128),
    object_name VARCHAR(256),
    full_sql_text TEXT,
    statement_text TEXT,
    input_buffer TEXT
);
